pool:
  vmImage: 'ubuntu-latest'

stages:
  #Build Java
  - stage: 'Maven'
    displayName: 'Maven Java'
    jobs:
      - job: 'BuildJAR'
        displayName: 'Java Application'
        steps:
          - template: build.yml
      
  - stage: 'CopyandPublish'
    displayName: 'Copy'
    jobs:
      - job: 'Publish'
        displayName: 'Publish'
        steps:
          - template: Java.yml
