pool:
  vmImage: 'ubuntu-latest'

stages:
  #Build Java
  - stage: 'Test'
    displayName: 'Test Result'
    jobs:
      - job: 'Test'
        displayName: 'Test Java Project'
        steps:
          - template: Test & code coverage.yml

  - stage: 'Build'
    displayName: 'Maven Java'
    jobs:
      - job: 'BuildJAR'
        displayName: 'Build Java Project'
        steps:
          - template: build.yml 