steps:
 - task: Maven@3
   inputs:
    mavenPomFile: '$(system.defaultWorkingDirectory)/SampleJavaApp/java-junit-sample/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
 - task: CopyFiles@2
   inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
    
  
 - task: PublishBuildArtifacts@1
   inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
